import { describe, it, expect } from 'vitest';
import { allCitySlugs, isKnownCity, countyForCity } from './jurisdictions.js';
import registry from '../data/registry.json';

describe('allCitySlugs', () => {
  it('returns a non-empty list', () => {
    expect(allCitySlugs().length).toBeGreaterThan(0);
  });

  it('includes greenville', () => {
    expect(allCitySlugs()).toContain('greenville');
  });

  it('includes charleston and north-charleston as separate slugs', () => {
    const slugs = allCitySlugs();
    expect(slugs).toContain('charleston');
    expect(slugs).toContain('north-charleston');
  });

  it('strips the place: prefix from every slug', () => {
    for (const slug of allCitySlugs()) {
      expect(slug.startsWith('place:')).toBe(false);
    }
  });

  it('contains no county ids', () => {
    for (const slug of allCitySlugs()) {
      expect(slug.startsWith('county:')).toBe(false);
    }
    expect(allCitySlugs()).not.toContain('county:greenville');
  });

  it('returns unique slugs', () => {
    const slugs = allCitySlugs();
    expect(new Set(slugs).size).toBe(slugs.length);
  });

  it('returns a frozen array so callers cannot mutate the allowlist', () => {
    expect(Object.isFrozen(allCitySlugs())).toBe(true);
  });
});

describe('isKnownCity', () => {
  it('returns true for greenville', () => {
    expect(isKnownCity('greenville')).toBe(true);
  });

  it('returns true for a multi-word slug like mount-pleasant', () => {
    expect(isKnownCity('mount-pleasant')).toBe(true);
  });

  it('returns false for a city outside the registry', () => {
    expect(isKnownCity('atlanta')).toBe(false);
  });

  it('returns false for the prefixed registry id', () => {
    expect(isKnownCity('place:greenville')).toBe(false);
  });

  it('returns false for capitalized input', () => {
    expect(isKnownCity('Greenville')).toBe(false);
  });

  it('returns false for the empty string', () => {
    expect(isKnownCity('')).toBe(false);
  });

  it('returns false for inherited Object property names', () => {
    expect(isKnownCity('constructor')).toBe(false);
    expect(isKnownCity('toString')).toBe(false);
    expect(isKnownCity('__proto__')).toBe(false);
  });
});

describe('countyForCity', () => {
  it('maps greenville to greenville', () => {
    expect(countyForCity('greenville')).toEqual({ ok: true, value: 'greenville' });
  });

  it('maps charleston to charleston', () => {
    expect(countyForCity('charleston')).toEqual({ ok: true, value: 'charleston' });
  });

  it('maps north-charleston to charleston, so city and county differ', () => {
    expect(countyForCity('north-charleston')).toEqual({ ok: true, value: 'charleston' });
  });

  it('maps mount-pleasant to charleston', () => {
    expect(countyForCity('mount-pleasant')).toEqual({ ok: true, value: 'charleston' });
  });

  it('lowercases a mixed-case county name like McCormick', () => {
    expect(countyForCity('mccormick')).toEqual({ ok: true, value: 'mccormick' });
  });

  it('returns unknown_city for a city outside the registry', () => {
    expect(countyForCity('atlanta')).toEqual({ ok: false, code: 'unknown_city' });
  });

  it('returns unknown_city for the prefixed registry id', () => {
    expect(countyForCity('place:greenville')).toEqual({ ok: false, code: 'unknown_city' });
  });
});

describe('registry consistency', () => {
  it('resolves every allowlisted slug to a lowercase county slug', () => {
    for (const slug of allCitySlugs()) {
      const result = countyForCity(slug);
      expect(result.ok).toBe(true);
      if (!result.ok) continue;
      expect(result.value.length).toBeGreaterThan(0);
      expect(result.value).toBe(result.value.toLowerCase());
      expect(result.value).not.toMatch(/\s/);
    }
  });

  // countyForCity lowercases the registry's `county` field and does nothing
  // else. That is only correct while every place: entry carries a bare
  // single-word county -- no embedded whitespace, no trailing "County".
  // registry.json is regenerated by a separate script, so assert the shape
  // here: if the convention ever changes, this fails loudly instead of
  // jurisdictions.ts silently emitting a county slug like "greenville county".
  it('gives every place: entry a bare single-word county, so lowercasing is the whole slug rule', () => {
    const entries = (registry as { jurisdictions?: Array<{ id?: unknown; county?: unknown }> })
      .jurisdictions ?? [];
    const places = entries.filter(
      (entry) => typeof entry.id === 'string' && entry.id.startsWith('place:'),
    );

    expect(places.length).toBeGreaterThan(0);

    for (const place of places) {
      expect(typeof place.county).toBe('string');
      const county = place.county as string;
      expect(county).toMatch(/^[A-Za-z]+$/);
      expect(county).not.toMatch(/county$/i);
    }
  });
});
